services:
  redis:
    image: redis:7.2
    restart: unless-stopped
    ports:
      - "${REDISPORT:-6379}:6379"
    command: [
      "redis-server",
      "--requirepass", "${REDIS_PASSWORD:-mysecretpassword}",
    ]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-mysecretpassword}", "PING"]
      interval: 5s
      timeout: 3s
      retries: 15
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
